### ISSUE TITLE
Streamz doesn't start anymore on kodi Libreelec

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.streamz#50]
Same bug as vtmgo addon -> https://github.com/add-ons/plugin.video.vtm.go/issues/342

error message is:

2023-01-02 20:29:58.579 T:704 ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'requests.exceptions.HTTPError'>
Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/streamz/tokens/refresh
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.streamz/addon_entry.py", line 19, in
run(argv)
File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 140, in run
routing.run(params)
File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
self._dispatch(self.path)
File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
view_func(**kwargs)
File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 22, in index
tokens = auth.get_tokens()
File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/auth.py", line 150, in get_tokens
response = util.http_post('https://lfvp-api.dpgmedia.net/streamz/tokens/refresh', data={
File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 83, in http_post
return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 183, in _request
response.raise_for_status()
File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/streamz/tokens/refresh
-->End of Python script error report<--

**Comment by keiem** [comment]
@mediaminister 

I tested your commits.  I can login again but I only see the "my_list" and "search" items.  When I chose "my_list" i get this error:

2023-01-04 19:37:07.299 T:6555    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.streamz.exceptions.UnavailableException'>
                                                   Error Contents: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/streamz/my-list
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 57, in http_get
                                                       return _request('GET', url=url, params=params, token=token, profile=profile, headers=headers)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 183, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/streamz/my-list
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 140, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 98, in show_mylist
                                                       Catalog().show_mylist()
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/modules/catalog.py", line 176, in show_mylist
                                                       mylist = self._api.get_mylist()
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/api.py", line 119, in get_mylist
                                                       response = util.http_get(API_ENDPOINT + '/%s/my-list' % (self._mode()),
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 62, in http_get
                                                       raise UnavailableException(exc)
                                                   resources.lib.streamz.exceptions.UnavailableException: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/streamz/my-list
                                                   -->End of Python script error report<--
                                                   
2023-01-04 19:37:08.095 T:6555     INFO <general>: Python interpreter stopped
2023-01-04 19:37:08.115 T:6558     INFO <general>: Skipped 1 duplicate messages..
2023-01-04 19:37:08.115 T:6558    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.streamz/catalog/mylist
2023-01-04 19:37:08.148 T:824     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamz/catalog/mylist) failed

Maybe it has something to do with removing my tokens?  I had to put the given code in login.streamz.be/activate and it was succesfull.

**Comment by mediaminister** [comment]
I'm sorry, but I currently have no time to look further into this. I don't use Streamz myself so I guess someone with a Streamz subscription should take a look at this.

**Comment by michaelarnauts** [comment]
@mediaminister thanks for the start! I'll take a look further.

**Comment by keiem** [comment]
If you give me a hint how to find out the new file structure of STREAMZ, I can give it a try also.  I checked your commits from the VTMGO addon, and everything looks rather the same between the STREAMZ and VTMGO addon.

**Comment by keiem** [comment]
@michaelarnauts 

I can view the filelist now, but i get errors on everything we try to watch.  Here is a example of the error:

2023-01-06 18:14:05.519 T:3683    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resources.lib.streamz.exceptions.UnavailableException'>
                                                   Error Contents: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/STREAMZ/programs/987a4467-2ac5-42b8-a3f3-be989ddc92df/seasons/1
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 57, in http_get
                                                       return _request('GET', url=url, params=params, token=token, profile=profile, headers=headers)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 183, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 960, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/STREAMZ/programs/987a4467-2ac5-42b8-a3f3-be989ddc92df/seasons/1
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 140, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 91, in show_recommendations_category
                                                       Catalog().show_recommendations_category(storefront, category)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/modules/catalog.py", line 157, in show_recommendations_category
                                                       result = self._api.get_storefront_category(storefront, category)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/api.py", line 110, in get_storefront_category
                                                       items.append(self._parse_program_teaser(item))
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/api.py", line 390, in _parse_program_teaser
                                                       program = self.get_program(item.get('target', {}).get('id'), cache=cache)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/api.py", line 227, in get_program
                                                       season_response = util.http_get(API_ENDPOINT + '/%s/programs/%s/seasons/%s' % (self._mode(), program_id, item_season),
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 62, in http_get
                                                       raise UnavailableException(exc)
                                                   resources.lib.streamz.exceptions.UnavailableException: 404 Client Error: Not Found for url: https://lfvp-api.dpgmedia.net/STREAMZ/programs/987a4467-2ac5-42b8-a3f3-be989ddc92df/seasons/1
                                                   -->End of Python script error report<--

**Comment by michaelarnauts** [comment]
You could try to download the auto-generated zip at https://github.com/add-ons/plugin.video.streamz/archive/refs/heads/api13.zip (can't create a real zip right now, I'm away my pc).

This is for my api13 branch. It should work, but might need some more work.

Sorry, shouldn't have closed this issue.

**Comment by keiem** [comment]
Indeed, this fixed it.  I just downloaded the master branch.  i didn't realize you made a separate branch for it.

**Comment by matti008** [comment]
Had the same issue, but is indeed fixed with this new build.

**Comment by michaelarnauts** [comment]
Merged into master. I'll create a new release with this fix.
