### ISSUE TITLE
error while opening streamz

### ISSUE THREAD

**Issue by keiem** [add-ons/plugin.video.streamz#61]
While opening streamz; I get this error: streamz fout contorleer het log voor meer informatie

Start the streamz addon

**Logs**
When I check the log, I get this error:

2024-06-30 21:06:13.805 T:790     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.HTTPError'>
                                                   Error Contents: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/STREAMZ/tokens/refresh
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.streamz/addon_entry.py", line 19, in <module>
                                                       run(argv)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 140, in run
                                                       routing.run(params)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/addon.py", line 22, in index
                                                       tokens = auth.get_tokens()
                                                                ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/auth.py", line 150, in get_tokens
                                                       response = util.http_post('https://lfvp-api.dpgmedia.net/STREAMZ/tokens/refresh', data={
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 83, in http_post
                                                       return _request('POST', url=url, params=params, form=form, data=data, token=token, profile=profile, headers=headers)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.streamz/resources/lib/streamz/util.py", line 183, in _request
                                                       response.raise_for_status()
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 1021, in raise_for_status
                                                       raise HTTPError(http_error_msg, response=self)
                                                   requests.exceptions.HTTPError: 426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/STREAMZ/tokens/refresh
                                                   -->End of Python script error report<--
                                                   

**System**
 - Addon version:1.1.4
 - Kodi version:20.3
 - Inputstream adaptive version:latest
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...):LibreElec
 - Special Hardware (RPI / Vero4K+ / ...):pineH64

**Comment by mantaalex** [comment]
Yeah i have error to please someone fix this

**Comment by mantaalex** [comment]
@dagwieers @michaelarnauts @mediaminister it would be great if its fixed again

**Comment by keiem** [comment]
If you update the API according the vtmgo addon, the error message is gone, but the catalog is empty.  If you use the search function, you don't get any results either.  Probably they changed the way the catalog works.

**Comment by keiem** [comment]
[plugin.video.streamz-fix.zip](https://github.com/user-attachments/files/16339982/plugin.video.streamz-fix.zip)

Try this one.  I based it on the fix from the vtm-go addon.  I don't think everything works, but "my list" does work.

**Comment by SirSFL** [comment]
> [plugin.video.streamz-fix.zip](https://github.com/user-attachments/files/16339982/plugin.video.streamz-fix.zip)
> 
> Try this one. I based it on the fix from the vtm-go addon. I don't think everything works, but "my list" does work.

I Installed your version today.
My list works and all programs are listed.
However, some programs won't play. I can hear the audio but no video is showing.
there seems to be a problem with the CDM.

**Comment by keiem** [comment]
It's a known problem.  It's all the stuff from paramount.  I already made a bug report for this some months ago.  But this addon isn't supported anymore and I don't have the knowledge to fix this.

**Comment by NofanTasi** [comment]
sorry to ask, is the original issue e.g.
426 Client Error: Upgrade Required for url: https://lfvp-api.dpgmedia.net/STREAMZ/tokens/refresh
resolved or is there a workaround?

**Comment by keiem** [comment]
Everything still works on my pc.  Did you try the fixed addon linked above?

**Comment by NofanTasi** [comment]
fair enough, but what is the official addon status ... why is there no fix?

**Comment by keiem** [comment]
No idea, according me, this plugin is dead...

**Comment by SirSFL** [comment]
Hate to see this plugin as 'dead'. 
I have some programming knowledge but this is just one level to hard for me alone :).
